import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../l10n/generated/app_localizations.dart';
import '../../state/config_draft.dart';
import '../../state/project_controller.dart';
import '_field.dart';

/// Phase 4: optional explicit topology graph. While the master switch
/// is off, the engine derives a default topology from the flat
/// arrays/inverters/batteries lists and the section stays a thin info
/// chip. Toggling on seeds the draft from the legacy adapter and reveals
/// editors for DC/AC buses, MPPTs (read-only), edges and battery
/// couplings (PRD FR-08; Architektur §4).
class TopologySection extends StatelessWidget {
  const TopologySection({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = context.watch<ProjectController>();
    final draft = controller.draft;
    final l = AppLocalizations.of(context);
    final topo = draft.topology;
    final inverterIds = [for (final i in draft.inverters) i.id];

    return Card(
      child: ExpansionTile(
        title: Text(l.topologyTitle),
        leading: const Icon(Icons.account_tree_outlined),
        initiallyExpanded: topo.enabled,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              SwitchListTile(
                key: const Key('topology-enable'),
                contentPadding: EdgeInsets.zero,
                title: Text(l.topologyEnable),
                value: topo.enabled,
                onChanged: (v) {
                  topo.enabled = v;
                  if (v && topo.dcBuses.isEmpty && topo.acBuses.isEmpty) {
                    topo.seedFromConfig(draft);
                  }
                  controller.touch();
                },
              ),
              if (!topo.enabled)
                Row(children: [
                  const Icon(Icons.info_outline, size: 16),
                  const SizedBox(width: 6),
                  Expanded(child: Text(
                    l.topologyAutoGeneratedInfo,
                    style: Theme.of(context).textTheme.bodySmall,
                  )),
                ])
              else ...[
                Align(
                  alignment: Alignment.centerLeft,
                  child: TextButton.icon(
                    key: const Key('topology-seed-from-legacy'),
                    onPressed: () {
                      topo.seedFromConfig(draft);
                      controller.touch();
                    },
                    icon: const Icon(Icons.auto_fix_high),
                    label: Text(l.topologySeedFromLegacy),
                  ),
                ),
                const SizedBox(height: 8),
                _DcBusesEditor(topo: topo, onChanged: controller.touch),
                const SizedBox(height: 12),
                _AcBusesEditor(topo: topo, onChanged: controller.touch),
                const SizedBox(height: 12),
                _MpptList(topo: topo),
                const SizedBox(height: 12),
                _EdgesEditor(topo: topo, onChanged: controller.touch),
                const SizedBox(height: 12),
                _CouplingsEditor(
                  topo: topo,
                  draft: draft,
                  inverterIds: inverterIds,
                  onChanged: controller.touch,
                ),
              ],
            ]),
          ),
        ],
      ),
    );
  }
}

class _DcBusesEditor extends StatelessWidget {
  const _DcBusesEditor({required this.topo, required this.onChanged});
  final TopologyGraphDraft topo;
  final VoidCallback onChanged;

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Expanded(child: Text(l.topologyDcBusesTitle, style: Theme.of(context).textTheme.titleSmall)),
        TextButton.icon(
          key: const Key('topology-add-dc-bus'),
          onPressed: () {
            final n = topo.dcBuses.length + 1;
            topo.dcBuses.add(DcBusDraft(id: 'dc-bus-$n'));
            onChanged();
          },
          icon: const Icon(Icons.add),
          label: Text(l.topologyAddDcBus),
        ),
      ]),
      for (var i = 0; i < topo.dcBuses.length; i++)
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 4),
          child: Row(children: [
            SizedBox(width: 180, child: StringField(
              key: ValueKey('topology-dc-${topo.dcBuses[i].id}-id'),
              label: l.fieldId, initialValue: topo.dcBuses[i].id, required: true,
              onChanged: (v) { topo.dcBuses[i].id = v; onChanged(); },
            )),
            const SizedBox(width: 8),
            SizedBox(width: 220, child: StringField(
              label: l.fieldLabel, initialValue: topo.dcBuses[i].label,
              onChanged: (v) { topo.dcBuses[i].label = v; onChanged(); },
            )),
            IconButton(
              tooltip: l.commonRemove,
              onPressed: () { topo.dcBuses.removeAt(i); onChanged(); },
              icon: const Icon(Icons.close),
            ),
          ]),
        ),
    ]);
  }
}

class _AcBusesEditor extends StatelessWidget {
  const _AcBusesEditor({required this.topo, required this.onChanged});
  final TopologyGraphDraft topo;
  final VoidCallback onChanged;

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Expanded(child: Text(l.topologyAcBusesTitle, style: Theme.of(context).textTheme.titleSmall)),
        TextButton.icon(
          key: const Key('topology-add-ac-bus'),
          onPressed: () {
            final n = topo.acBuses.length + 1;
            topo.acBuses.add(AcBusDraft(id: 'ac-bus-$n'));
            onChanged();
          },
          icon: const Icon(Icons.add),
          label: Text(l.topologyAddAcBus),
        ),
      ]),
      for (var i = 0; i < topo.acBuses.length; i++)
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 4),
          child: Row(children: [
            SizedBox(width: 180, child: StringField(
              key: ValueKey('topology-ac-${topo.acBuses[i].id}-id'),
              label: l.fieldId, initialValue: topo.acBuses[i].id, required: true,
              onChanged: (v) { topo.acBuses[i].id = v; onChanged(); },
            )),
            const SizedBox(width: 8),
            SizedBox(width: 220, child: StringField(
              label: l.fieldLabel, initialValue: topo.acBuses[i].label,
              onChanged: (v) { topo.acBuses[i].label = v; onChanged(); },
            )),
            IconButton(
              tooltip: l.commonRemove,
              onPressed: () { topo.acBuses.removeAt(i); onChanged(); },
              icon: const Icon(Icons.close),
            ),
          ]),
        ),
    ]);
  }
}

class _MpptList extends StatelessWidget {
  const _MpptList({required this.topo});
  final TopologyGraphDraft topo;

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(l.topologyMpptTitle, style: Theme.of(context).textTheme.titleSmall),
      if (topo.mppts.isEmpty)
        Text(l.topologyMpptEmpty, style: Theme.of(context).textTheme.bodySmall)
      else
        for (final m in topo.mppts)
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 2),
            child: Text('• ${m.id} → ${m.inverterId}',
                style: Theme.of(context).textTheme.bodySmall),
          ),
    ]);
  }
}

class _EdgesEditor extends StatelessWidget {
  const _EdgesEditor({required this.topo, required this.onChanged});
  final TopologyGraphDraft topo;
  final VoidCallback onChanged;

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Expanded(child: Text(l.topologyEdgesTitle, style: Theme.of(context).textTheme.titleSmall)),
        TextButton.icon(
          key: const Key('topology-add-edge'),
          onPressed: () {
            topo.edges.add(BusEdgeDraft(fromId: '', toId: ''));
            onChanged();
          },
          icon: const Icon(Icons.add),
          label: Text(l.topologyAddEdge),
        ),
      ]),
      for (var i = 0; i < topo.edges.length; i++)
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 4),
          child: Wrap(spacing: 8, runSpacing: 8, crossAxisAlignment: WrapCrossAlignment.center, children: [
            SizedBox(width: 160, child: StringField(
              label: l.topologyEdgeFrom, initialValue: topo.edges[i].fromId, required: true,
              onChanged: (v) { topo.edges[i].fromId = v; onChanged(); },
            )),
            SizedBox(width: 160, child: StringField(
              label: l.topologyEdgeTo, initialValue: topo.edges[i].toId, required: true,
              onChanged: (v) { topo.edges[i].toId = v; onChanged(); },
            )),
            SizedBox(width: 140, child: NumberField(
              label: l.topologyEdgeEfficiency, suffix: '0..1',
              initialValue: topo.edges[i].efficiency, min: 0.001, max: 1,
              onChanged: (v) { if (v != null) { topo.edges[i].efficiency = v; onChanged(); } },
            )),
            SizedBox(width: 160, child: NumberField(
              label: l.topologyEdgeMaxPowerKw, suffix: 'kW',
              initialValue: topo.edges[i].maxPowerKw, min: 0, allowNull: true,
              onChanged: (v) { topo.edges[i].maxPowerKw = v; onChanged(); },
            )),
            SizedBox(width: 140, child: NumberField(
              label: l.topologyEdgeStandbyW, suffix: 'W',
              initialValue: topo.edges[i].standbyW, min: 0,
              onChanged: (v) { if (v != null) { topo.edges[i].standbyW = v; onChanged(); } },
            )),
            IconButton(
              tooltip: l.commonRemove,
              onPressed: () { topo.edges.removeAt(i); onChanged(); },
              icon: const Icon(Icons.close),
            ),
          ]),
        ),
    ]);
  }
}

class _CouplingsEditor extends StatelessWidget {
  const _CouplingsEditor({
    required this.topo,
    required this.draft,
    required this.inverterIds,
    required this.onChanged,
  });

  final TopologyGraphDraft topo;
  final ConfigDraft draft;
  final List<String> inverterIds;
  final VoidCallback onChanged;

  BatteryCouplingDraft _ensureCouplingFor(String batteryId) {
    for (final c in topo.couplings) {
      if (c.batteryId == batteryId) return c;
    }
    final c = BatteryCouplingDraft(batteryId: batteryId);
    topo.couplings.add(c);
    return c;
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    final dcBusIds = [for (final b in topo.dcBuses) b.id];
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(l.topologyCouplingsTitle, style: Theme.of(context).textTheme.titleSmall),
      if (draft.batteries.isEmpty)
        Text(l.topologyCouplingsEmpty, style: Theme.of(context).textTheme.bodySmall)
      else
        for (final battery in draft.batteries) ...[
          const SizedBox(height: 4),
          Builder(builder: (context) {
            final coupling = _ensureCouplingFor(battery.id);
            return Wrap(spacing: 8, runSpacing: 8, crossAxisAlignment: WrapCrossAlignment.center, children: [
              SizedBox(width: 180, child: Text(battery.id, style: Theme.of(context).textTheme.bodyMedium)),
              SegmentedButton<bool>(
                segments: [
                  ButtonSegment(value: true, label: Text(l.topologyCouplingAc)),
                  ButtonSegment(value: false, label: Text(l.topologyCouplingDc)),
                ],
                selected: {coupling.acCoupled},
                onSelectionChanged: (v) {
                  coupling.acCoupled = v.first;
                  // Drop the now-hidden picker's selection so a switch
                  // back to AC doesn't silently apply a stale dcBusId,
                  // and a DC-coupled battery doesn't keep a stale
                  // inverterId that would otherwise feed the engine's
                  // AC cap path.
                  if (coupling.acCoupled) {
                    coupling.dcBusId = null;
                  } else {
                    coupling.inverterId = null;
                  }
                  onChanged();
                },
              ),
              if (!coupling.acCoupled)
                SizedBox(
                  width: 220,
                  child: DropdownButtonFormField<String>(
                    key: Key('topology-coupling-${battery.id}-dcbus'),
                    isExpanded: true,
                    initialValue: dcBusIds.contains(coupling.dcBusId) ? coupling.dcBusId : null,
                    decoration: InputDecoration(labelText: l.topologyCouplingDcBus, isDense: true),
                    items: [
                      for (final id in dcBusIds) DropdownMenuItem(value: id, child: Text(id)),
                    ],
                    onChanged: (v) {
                      coupling.dcBusId = v;
                      onChanged();
                    },
                  ),
                ),
              if (coupling.acCoupled)
                SizedBox(
                  width: 240,
                  child: DropdownButtonFormField<String?>(
                    key: Key('topology-coupling-${battery.id}-inverter'),
                    isExpanded: true,
                    initialValue: inverterIds.contains(coupling.inverterId) ? coupling.inverterId : null,
                    decoration: InputDecoration(
                      labelText: l.topologyCouplingInverter,
                      isDense: true,
                      helperText: l.topologyCouplingInverterHelp,
                    ),
                    items: [
                      DropdownMenuItem<String?>(value: null, child: Text(l.topologyCouplingInverterNone)),
                      for (final id in inverterIds) DropdownMenuItem<String?>(value: id, child: Text(id)),
                    ],
                    onChanged: (v) {
                      coupling.inverterId = v;
                      onChanged();
                    },
                  ),
                ),
            ]);
          }),
        ],
    ]);
  }
}
